In [24]:
import pandas as pd
df = pd.read_csv("/content/sales_data2.csv")
df.head()

  Order ID;Date;Region;Product;Quantity;Revenue;Expenses
0  C100;01/01/2020;Gauteng ;Laptop;10;R50 000;R13...
1  C101;02/01/2020;Gauteng ;Phone ;12;R53 000;R20...
2  C102;03/01/2020;Gauteng ;Phone ;100;R78 000;R5...
3    C103;04/01/2020;Gauteng ;iPad;9;R40 000;R16 432
4    C104;05/01/2020;Gauteng ;iPad;2;R20 000;R25 600

In [28]:
import pandas as pd
import sqlite3
conn = sqlite3.connect("/content?sales_data2.db")
df.to_sql("sales", conn, if_exists="replace", index=False)

364

In [29]:
query = """
SELECT *
FROM sales
LIMIT 10;
"""

pd.read_sql(query, conn)

  Order ID        Date        Region Product  Quantity  Revenue Expenses
0     C100  01/01/2020      Gauteng   Laptop        10  R50 000  R13 500
1     C101  02/01/2020      Gauteng   Phone         12  R53 000  R20 799
2     C102  03/01/2020      Gauteng   Phone        100  R78 000  R50 000
3     C103  04/01/2020      Gauteng     iPad         9  R40 000  R16 432
4     C104  05/01/2020      Gauteng     iPad         2  R20 000  R25 600
5     C105  06/01/2020      Gauteng     iPad         4  R25 000     R600
6     C106  07/01/2020      Gauteng     iPad        16  R43 000  R31 798
7     C107  08/01/2020  Western Cape    iPad        28  R67 000       R0
8     C108  09/01/2020  Western Cape  Laptop        31  R78 300       R0
9     C109  10/01/2020  Western Cape  Laptop         2  R25 000       R0

In [30]:
df = pd.read_csv("/content/sales_data2.csv", sep=";")
print(df.columns.tolist())

['Order ID', 'Date', 'Region', 'Product', 'Quantity', 'Revenue', 'Expenses']

In [31]:
query = """
SELECT
    Region,
    SUM(Revenue) AS Total_Revenue
FROM sales
GROUP BY Region
ORDER BY Total_Revenue DESC;
"""

pd.read_sql(query, conn)

         Region  Total_Revenue
0  Western Cape           68.0
1      Gauteng             0.0
2  Eastern Cape            0.0

In [32]:
print(df["Revenue"].dtype)
print(df["Revenue"].head(10))

object
0    R50 000
1    R53 000
2    R78 000
3    R40 000
4    R20 000
5    R25 000
6    R43 000
7    R67 000
8    R78 300
9    R25 000
Name: Revenue, dtype: object

In [33]:
import re
def clean_currency(val):
     val = str(val)
     val = re.sub(r"[^\d.]", "", val)
     return float(val) if val else 0.0

df["Revenue"] = df["Revenue"].apply(clean_currency)
df["Expenses"] = df["Expenses"].apply(clean_currency)

In [34]:
conn = sqlite3.connect("/content/sales_data.db")
df.to_sql("sales", conn, if_exists="replace", index=False )

364

In [35]:
pd.to_datetime(df["Date"], dayfirst=True, errors="coerce")
mask = pd.to_datetime(df["Date"], dayfirst=True, errors="coerce").isna()
print(df[mask])

Empty DataFrame
Columns: [Order ID, Date, Region, Product, Quantity, Revenue, Expenses]
Index: []

In [36]:
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
conn = sqlite3.connect("/content/sales_data.db")
df.to_sql("sales", conn, if_exists="replace", index=False)

364

In [37]:
query = """
SELECT
    Region,
    SUM(Revenue) AS Total_Revenue
FROM sales
GROUP BY Region
ORDER BY Total_Revenue DESC;
"""
pd.read_sql(query, conn)

         Region  Total_Revenue
0  Western Cape      6389106.0
1      Gauteng       5159461.0
2  Eastern Cape      4465775.0

In [38]:
query = """
SELECT SUM(Revenue) AS Total_Revenue
FROM sales;
"""
pd.read_sql(query, conn)

   Total_Revenue
0     16014342.0

In [39]:
query = """
SELECT SUM (Expenses) AS Total_Expenses
FROM sales;
"""
pd.read_sql(query, conn)

   Total_Expenses
0       4830503.0

In [40]:
query = """
SELECT SUM(Revenue) - SUM(Expenses) AS Total_Profit
FROM sales;
"""
pd.read_sql(query, conn)

   Total_Profit
0    11183839.0

In [41]:
query = """
SELECT
    strftime('%Y-%m', Date) AS Month,
    SUM(Revenue) AS Total_Revenue
FROM sales
GROUP BY Month
ORDER BY Month;
"""
pd.read_sql(query, conn)

      Month  Total_Revenue
0   2020-01      1330767.0
1   2020-02      1155743.0
2   2020-03      1185604.0
3   2020-04      1196467.0
4   2020-05      1450620.0
5   2020-06      1520775.0
6   2020-07      1736854.0
7   2020-08      1481189.0
8   2020-09       798969.0
9   2020-10      1402289.0
10  2020-11       892290.0
11  2020-12      1862775.0

In [45]:
query = """
SELECT
     strftime('%Y-%m', Date) AS Month,
     SUM(Revenue) - SUM(Expenses) AS Total_Profit
FROM sales
GROUP BY Month
ORDER BY Month;
"""
pd.read_sql(query, conn)

      Month  Total_Profit
0   2020-01      990898.0
1   2020-02      986409.0
2   2020-03      728320.0
3   2020-04      939379.0
4   2020-05     1152793.0
5   2020-06     1181937.0
6   2020-07      760420.0
7   2020-08      868271.0
8   2020-09      605137.0
9   2020-10     1022312.0
10  2020-11      729892.0
11  2020-12     1218071.0

In [46]:
query = """
SELECT
    Region,
    SUM(Revenue) - SUM(Expenses) AS Total_Profit
FROM sales
GROUP BY Region
ORDER BY Total_Profit DESC;
"""
pd.read_sql(query, conn)

         Region  Total_Profit
0  Western Cape     4533039.0
1      Gauteng      3536939.0
2  Eastern Cape     3113861.0

In [47]:
query = """
SELECT
    Product,
    SUM(Revenue) AS Total_Revenue
FROM sales
GROUP BY Product
ORDER BY Total_Revenue DESC;
"""
pd.read_sql(query, conn)

  Product  Total_Revenue
0  Laptop      5799232.0
1    iPad      5249380.0
2  Phone       4965730.0

In [48]:
query = """
SELECT
    Product,
    SUM(Quantity) AS Units_Sold
FROM sales
GROUP BY Product
ORDER BY Units_Sold DESC;
"""
pd.read_sql(query, conn)

  Product  Units_Sold
0  Phone         2219
1  Laptop        1540
2    iPad        1529

In [50]:
query = """
SELECT
     AVG(Revenue) AS Avg_Revenue_Per_Order
FROM sales;
"""
pd.read_sql(query, conn)

   Avg_Revenue_Per_Order
0           43995.445055

In [51]:
query = """
SELECT *
FROM sales
ORDER BY Revenue DESC
LIMIT 1;
"""
pd.read_sql(query, conn)

,Order ID,Date,Region,Product,Quantity,Revenue,Expenses
0,C276,2020-06-27 00:00:00,Western Cape,Laptop,30,128000.0,0.0

In [52]:
query = """
SELECT *
FROM sales
ORDER BY Revenue ASC
LIMIT 1;
"""
pd.read_sql(query, conn)

  Order ID                 Date    Region Product  Quantity  Revenue  Expenses
0     C153  2020-02-23 00:00:00  Gauteng   Phone          1   8000.0     400.0

In [53]:
query = """
SELECT
    Region,
    COUNT(*) AS Number_of_Orders
FROM sales
GROUP BY Region
ORDER BY Number_of_Orders DESC;
"""
pd.read_sql(query, conn)

         Region  Number_of_Orders
0  Western Cape               141
1      Gauteng                123
2  Eastern Cape               100

In [55]:
query = """
SELECT
    Product,
    AVG((Revenue-Expenses) * 1.0 / Revenue) * 100 AS Avg_Profit_Margin_Percent
FROM sales
GROUP BY Product
ORDER BY Avg_Profit_Margin_Percent DESC;
"""
pd.read_sql(query, conn)

  Product  Avg_Profit_Margin_Percent
0  Laptop                  73.275745
1    iPad                  64.341667
2  Phone                   56.878222

In [56]:
query = """
SELECT
     strftime('%Y', Date) AS Year,
     ((CAST(strftime('%m', Date) AS INTEGER) - 1) / 3) + 1 AS Quarter,
     SUM(Revenue) AS Total_Revenue
FROM sales
GROUP BY Year, Quarter
ORDER BY Year, Quarter;
"""
pd.read_sql(query, conn)

   Year  Quarter  Total_Revenue
0  2020        1      3672114.0
1  2020        2      4167862.0
2  2020        3      4017012.0
3  2020        4      4157354.0

In [58]:
query = """
SELECT
    strftime('%Y-%m', Date) AS Month,
    SUM(Revenue) AS Total_Revenue
FROM sales
GROUP BY Month
ORDER BY Total_Revenue DESC
LIMIT 5;
"""
pd.read_sql(query, conn)

     Month  Total_Revenue
0  2020-12      1862775.0
1  2020-07      1736854.0
2  2020-06      1520775.0
3  2020-08      1481189.0
4  2020-05      1450620.0

In [59]:
query = """
SELECT
    Product,
    SUM(Revenue) AS Total_Revenue
FROM sales
GROUP BY Product
HAVING SUM(Revenue) > 100000
ORDER BY Total_Revenue DESC;
"""
pd.read_sql(query, conn)

  Product  Total_Revenue
0  Laptop      5799232.0
1    iPad      5249380.0
2  Phone       4965730.0

In [60]:
query = """
SELECT
    Region,
    SUM(Revenue) - SUM(Expenses) AS Total_Profit
FROM sales
GROUP BY Region
ORDER BY Total_Profit DESC
LIMIT 1;
"""
pd.read_sql(query, conn)

         Region  Total_Profit
0  Western Cape     4533039.0